#!/usr/bin/env python3
"""
FINAL COMPREHENSIVE Korean Translation
Translates EVERYTHING to Korean except code blocks and technical terms
"""

import os
import re
from pathlib import Path
from typing import Dict, Tuple

# MASSIVE translation dictionary - must translate EVERYTHING
MEGA_TRANSLATIONS = {
    # Common verbs - present tense
    "improves": "개선합니다", "improved": "개선된",
    "replaces": "대체합니다", "replaced": "대체된", "replacing": "대체하는",
    "includes": "포함합니다", "included": "포함된", "including": "포함하여",
    "features": "기능", "featured": "특징적인",
    "supports": "지원합니다", "supported": "지원되는",
    "enables": "활성화합니다", "enabled": "활성화된",
    "allows": "허용합니다", "allowed": "허용된",
    "provides": "제공합니다", "provided": "제공된",
    "requires": "필요합니다", "required": "필수", "requirement": "요구사항", "requirements": "요구사항",
    "offers": "제공합니다", "offered": "제공된",
    "delivers": "전달합니다", "delivered": "전달된", "delivery": "전달",
    "processes": "처리합니다", "processed": "처리된", "processing": "처리",
    "handles": "처리합니다", "handled": "처리된", "handling": "처리",
    "manages": "관리합니다", "managed": "관리되는", "management": "관리",
    "controls": "제어합니다", "controlled": "제어된", "controlling": "제어하는",
    "monitors": "모니터링합니다", "monitored": "모니터링되는", "monitoring": "모니터링",
    "tracks": "추적합니다", "tracked": "추적된", "tracking": "추적",
    "validates": "검증합니다", "validated": "검증된", "validation": "검증",
    "verifies": "확인합니다", "verified": "확인된", "verification": "확인",
    "ensures": "보장합니다", "ensured": "보장된", "ensuring": "보장하는",
    "guarantees": "보증합니다", "guaranteed": "보증된",
    "maintains": "유지합니다", "maintained": "유지되는", "maintenance": "유지보수",
    "preserves": "보존합니다", "preserved": "보존된",
    "protects": "보호합니다", "protected": "보호된", "protection": "보호",
    "secures": "보안합니다", "secured": "보안된",
    "implements": "구현합니다", "implemented": "구현된", "implementation": "구현",
    "executes": "실행합니다", "executed": "실행된", "execution": "실행",
    "performs": "수행합니다", "performed": "수행된", "performance": "성능",
    "operates": "작동합니다", "operated": "작동하는", "operation": "작업", "operations": "작업",
    "functions": "기능합니다", "functional": "기능적인", "functionality": "기능",
    "works": "작동합니다", "worked": "작동한", "working": "작업",
    "runs": "실행합니다", "running": "실행 중",
    "builds": "구축합니다", "built": "구축된", "building": "구축",
    "creates": "생성합니다", "created": "생성된", "creating": "생성하는", "creation": "생성",
    "generates": "생성합니다", "generated": "생성된", "generation": "생성",
    "produces": "생산합니다", "produced": "생산된", "producing": "생산하는",
    "develops": "개발합니다", "developed": "개발된", "development": "개발",
    "designs": "설계합니다", "designed": "설계된", "design": "설계",
    "architects": "아키텍처를 설계합니다",
    "plans": "계획합니다", "planned": "계획된", "planning": "계획",
    "defines": "정의합니다", "defined": "정의된", "definition": "정의",
    "specifies": "지정합니다", "specified": "지정된", "specification": "사양",
    "configures": "구성합니다", "configured": "구성된", "configuration": "구성",
    "sets up": "설정합니다", "setup": "설정", "setting up": "설정하는",
    "establishes": "설정합니다", "established": "설정된",
    "initializes": "초기화합니다", "initialized": "초기화된", "initialization": "초기화",
    "prepares": "준비합니다", "prepared": "준비된", "preparation": "준비",
    "organizes": "구성합니다", "organized": "구성된", "organization": "구성",
    "structures": "구조화합니다", "structured": "구조화된", "structure": "구조",
    "arranges": "배열합니다", "arranged": "배열된", "arrangement": "배열",
    "coordinates": "조정합니다", "coordinated": "조정된", "coordination": "조정",
    "orchestrates": "오케스트레이션합니다", "orchestrated": "오케스트레이션된", "orchestration": "오케스트레이션",
    "synchronizes": "동기화합니다", "synchronized": "동기화된", "synchronization": "동기화",
    "integrates": "통합합니다", "integrated": "통합된", "integration": "통합",
    "combines": "결합합니다", "combined": "결합된", "combining": "결합하는",
    "merges": "병합합니다", "merged": "병합된", "merging": "병합하는",
    "connects": "연결합니다", "connected": "연결된", "connection": "연결",
    "links": "연결합니다", "linked": "연결된",
    "joins": "결합합니다", "joined": "결합된",
    "couples": "결합합니다", "coupled": "결합된", "coupling": "결합",
    "binds": "바인딩합니다", "bound": "바인딩된", "binding": "바인딩",
    "attaches": "첨부합니다", "attached": "첨부된", "attachment": "첨부",
    "deploys": "배포합니다", "deployed": "배포된", "deployment": "배포",
    "releases": "릴리스합니다", "released": "릴리스된", "release": "릴리스",
    "publishes": "게시합니다", "published": "게시된", "publishing": "게시",
    "distributes": "배포합니다", "distributed": "분산", "distribution": "배포",
    "migrates": "마이그레이션합니다", "migrated": "마이그레이션된", "migration": "마이그레이션",
    "upgrades": "업그레이드합니다", "upgraded": "업그레이드된", "upgrade": "업그레이드",
    "updates": "업데이트합니다", "updated": "업데이트된", "update": "업데이트",
    "modifies": "수정합니다", "modified": "수정된", "modification": "수정",
    "changes": "변경합니다", "changed": "변경된", "change": "변경",
    "alters": "변경합니다", "altered": "변경된",
    "transforms": "변환합니다", "transformed": "변환된", "transformation": "변환",
    "converts": "변환합니다", "converted": "변환된", "conversion": "변환",
    "translates": "번역합니다", "translated": "번역된", "translation": "번역",
    "adapts": "적응합니다", "adapted": "적응된", "adaptation": "적응",
    "adjusts": "조정합니다", "adjusted": "조정된", "adjustment": "조정",
    "customizes": "사용자 정의합니다", "customized": "사용자 정의된", "customization": "사용자 정의",
    "personalizes": "개인화합니다", "personalized": "개인화된", "personalization": "개인화",
    "optimizes": "최적화합니다", "optimized": "최적화된", "optimization": "최적화",
    "enhances": "향상합니다", "enhanced": "향상된", "enhancement": "향상",
    "refines": "정제합니다", "refined": "정제된",
    "polishes": "다듬습니다", "polished": "다듬어진",
    "tests": "테스트합니다", "tested": "테스트된", "testing": "테스트",
    "validates": "검증합니다", "validated": "검증된",
    "verifies": "확인합니다", "verified": "확인된",
    "checks": "확인합니다", "checked": "확인된", "checking": "확인",
    "reviews": "검토합니다", "reviewed": "검토된", "reviewing": "검토하는",
    "audits": "감사합니다", "audited": "감사된", "auditing": "감사",
    "inspects": "검사합니다", "inspected": "검사된", "inspection": "검사",
    "examines": "조사합니다", "examined": "조사된", "examination": "조사",
    "analyzes": "분석합니다", "analyzed": "분석된", "analysis": "분석",
    "evaluates": "평가합니다", "evaluated": "평가된", "evaluation": "평가",
    "assesses": "평가합니다", "assessed": "평가된", "assessment": "평가",
    "measures": "측정합니다", "measured": "측정된", "measurement": "측정",
    "debugs": "디버깅합니다", "debugged": "디버깅된", "debugging": "디버깅",
    "troubleshoots": "문제를 해결합니다", "troubleshooted": "문제 해결된", "troubleshooting": "문제 해결",
    "diagnoses": "진단합니다", "diagnosed": "진단된", "diagnosis": "진단",
    "fixes": "수정합니다", "fixed": "수정된", "fixing": "수정하는",
    "resolves": "해결합니다", "resolved": "해결된", "resolving": "해결하는", "resolution": "해결",
    "repairs": "복구합니다", "repaired": "복구된",
    "corrects": "수정합니다", "corrected": "수정된", "correction": "수정",
    "refactors": "리팩토링합니다", "refactored": "리팩토링된", "refactoring": "리팩토링",
    "restructures": "재구성합니다", "restructured": "재구성된",
    "reorganizes": "재구성합니다", "reorganized": "재구성된",
    "cleans": "정리합니다", "cleaned": "정리된", "cleaning": "정리",
    "simplifies": "단순화합니다", "simplified": "단순화된",
    "streamlines": "간소화합니다", "streamlined": "간소화된",
    "automates": "자동화합니다", "automated": "자동화된", "automation": "자동화",
    "schedules": "예약합니다", "scheduled": "예약된", "scheduling": "예약",
    "triggers": "트리거합니다", "triggered": "트리거된",
    "initiates": "시작합니다", "initiated": "시작된",
    "starts": "시작합니다", "started": "시작된", "starting": "시작하는",
    "begins": "시작합니다", "begun": "시작된", "beginning": "시작",
    "launches": "시작합니다", "launched": "시작된", "launching": "시작하는",
    "stops": "중지합니다", "stopped": "중지된", "stopping": "중지",
    "ends": "종료합니다", "ended": "종료된", "ending": "종료",
    "terminates": "종료합니다", "terminated": "종료된", "termination": "종료",
    "completes": "완료합니다", "completed": "완료된", "completion": "완료",
    "finishes": "완료합니다", "finished": "완료된",
    "concludes": "마무리합니다", "concluded": "마무리된",
    "pauses": "일시 중지합니다", "paused": "일시 중지된",
    "resumes": "재개합니다", "resumed": "재개된",
    "continues": "계속합니다", "continued": "계속된",
    "proceeds": "진행합니다", "proceeded": "진행된",
    "progresses": "진행합니다", "progressed": "진행된", "progress": "진행",
    "advances": "진전합니다", "advanced": "고급", "advancing": "진전하는",
    "scales": "확장합니다", "scaled": "확장된", "scaling": "확장",
    "grows": "성장합니다", "grown": "성장한", "growth": "성장",
    "expands": "확장합니다", "expanded": "확장된", "expansion": "확장",
    "extends": "확장합니다", "extended": "확장된", "extension": "확장",
    "increases": "증가합니다", "increased": "증가된", "increasing": "증가하는",
    "decreases": "감소합니다", "decreased": "감소된", "decreasing": "감소하는",
    "reduces": "감소합니다", "reduced": "감소된", "reduction": "감소",
    "minimizes": "최소화합니다", "minimized": "최소화된",
    "maximizes": "최대화합니다", "maximized": "최대화된",
    "limits": "제한합니다", "limited": "제한된", "limiting": "제한하는",
    "restricts": "제한합니다", "restricted": "제한된", "restriction": "제한",
    "constrains": "제약합니다", "constrained": "제약된", "constraint": "제약",
    "prevents": "방지합니다", "prevented": "방지된", "prevention": "방지",
    "blocks": "차단합니다", "blocked": "차단된", "blocking": "차단",
    "filters": "필터링합니다", "filtered": "필터링된", "filtering": "필터링",
    "screens": "선별합니다", "screened": "선별된",
    "selects": "선택합니다", "selected": "선택된", "selection": "선택",
    "chooses": "선택합니다", "chosen": "선택된", "choosing": "선택하는",
    "picks": "선택합니다", "picked": "선택된",
    "finds": "찾습니다", "found": "찾은", "finding": "찾는",
    "locates": "찾습니다", "located": "위치한", "location": "위치",
    "discovers": "발견합니다", "discovered": "발견된", "discovery": "발견",
    "detects": "감지합니다", "detected": "감지된", "detection": "감지",
    "identifies": "식별합니다", "identified": "식별된", "identification": "식별",
    "recognizes": "인식합니다", "recognized": "인식된", "recognition": "인식",
    "determines": "결정합니다", "determined": "결정된",
    "decides": "결정합니다", "decided": "결정된", "decision": "결정",
    "resolves": "해결합니다", "resolved": "해결된",
    "calculates": "계산합니다", "calculated": "계산된", "calculation": "계산",
    "computes": "계산합니다", "computed": "계산된", "computation": "계산",
    "evaluates": "평가합니다", "evaluated": "평가된",
    "processes": "처리합니다", "processed": "처리된",
    "renders": "렌더링합니다", "rendered": "렌더링된", "rendering": "렌더링",
    "displays": "표시합니다", "displayed": "표시된", "displaying": "표시하는",
    "shows": "표시합니다", "shown": "표시된", "showing": "표시하는",
    "presents": "제시합니다", "presented": "제시된", "presentation": "프레젠테이션",
    "demonstrates": "시연합니다", "demonstrated": "시연된", "demonstration": "시연",
    "illustrates": "설명합니다", "illustrated": "설명된", "illustration": "설명",
    "explains": "설명합니다", "explained": "설명된", "explanation": "설명",
    "describes": "설명합니다", "described": "설명된", "description": "설명",
    "documents": "문서화합니다", "documented": "문서화된", "documentation": "문서화",
    "records": "기록합니다", "recorded": "기록된", "recording": "기록",
    "logs": "로깅합니다", "logged": "로깅된", "logging": "로깅",
    "captures": "캡처합니다", "captured": "캡처된", "capturing": "캡처하는",
    "stores": "저장합니다", "stored": "저장된", "storage": "저장소",
    "saves": "저장합니다", "saved": "저장된", "saving": "저장하는",
    "persists": "유지합니다", "persisted": "유지된", "persistence": "지속성",
    "caches": "캐시합니다", "cached": "캐시된", "caching": "캐싱",
    "retrieves": "검색합니다", "retrieved": "검색된", "retrieval": "검색",
    "fetches": "가져옵니다", "fetched": "가져온", "fetching": "가져오는",
    "loads": "로드합니다", "loaded": "로드된", "loading": "로드",
    "reads": "읽습니다", "read": "읽은", "reading": "읽는",
    "writes": "씁니다", "written": "작성된", "writing": "작성",
    "sends": "전송합니다", "sent": "전송된", "sending": "전송하는",
    "receives": "수신합니다", "received": "수신된", "receiving": "수신하는",
    "transmits": "전송합니다", "transmitted": "전송된", "transmission": "전송",
    "transfers": "전송합니다", "transferred": "전송된", "transfer": "전송",
    "delivers": "전달합니다", "delivered": "전달된",
    "publishes": "게시합니다", "published": "게시된",
    "subscribes": "구독합니다", "subscribed": "구독된", "subscription": "구독",
    "listens": "리스닝합니다", "listened": "리스닝된", "listening": "리스닝",
    "watches": "관찰합니다", "watched": "관찰된", "watching": "관찰하는",
    "observes": "관찰합니다", "observed": "관찰된", "observation": "관찰",
    "monitors": "모니터링합니다", "monitored": "모니터링된",
    "tracks": "추적합니다", "tracked": "추적된",
    "traces": "추적합니다", "traced": "추적된", "tracing": "추적",
    "follows": "따릅니다", "followed": "따르는", "following": "다음",
    "routes": "라우팅합니다", "routed": "라우팅된", "routing": "라우팅",
    "directs": "지시합니다", "directed": "지시된", "direction": "방향",
    "forwards": "전달합니다", "forwarded": "전달된", "forwarding": "전달",
    "redirects": "리디렉션합니다", "redirected": "리디렉션된", "redirection": "리디렉션",
    "proxies": "프록시합니다", "proxied": "프록시된",
    "balances": "균형을 맞춥니다", "balanced": "균형된", "balancing": "균형",
    "distributes": "분산합니다", "distributed": "분산",
    "partitions": "분할합니다", "partitioned": "분할된", "partitioning": "분할",
    "shards": "샤드합니다", "sharded": "샤드된", "sharding": "샤딩",
    "replicates": "복제합니다", "replicated": "복제된", "replication": "복제",
    "mirrors": "미러링합니다", "mirrored": "미러링된", "mirroring": "미러링",
    "backs up": "백업합니다", "backed up": "백업된", "backup": "백업",
    "restores": "복원합니다", "restored": "복원된", "restoration": "복원",
    "recovers": "복구합니다", "recovered": "복구된", "recovery": "복구",
    "rolls back": "롤백합니다", "rolled back": "롤백된", "rollback": "롤백",
    "reverts": "되돌립니다", "reverted": "되돌린",
    "retries": "재시도합니다", "retried": "재시도된", "retry": "재시도",
    "repeats": "반복합니다", "repeated": "반복된", "repeating": "반복하는",
    "iterates": "반복합니다", "iterated": "반복된", "iteration": "반복",
    "loops": "루프합니다", "looped": "루프된", "looping": "루프",
    "cycles": "순환합니다", "cycled": "순환된", "cycling": "순환",
    "queues": "대기열에 넣습니다", "queued": "대기열에 있는", "queueing": "대기열",
    "stacks": "스택합니다", "stacked": "스택된", "stacking": "스택",
    "pools": "풀링합니다", "pooled": "풀링된", "pooling": "풀링",
    "batches": "배치합니다", "batched": "배치된", "batching": "배치",
    "chunks": "청크합니다", "chunked": "청크된", "chunking": "청킹",
    "groups": "그룹화합니다", "grouped": "그룹화된", "grouping": "그룹화",
    "clusters": "클러스터링합니다", "clustered": "클러스터링된", "clustering": "클러스터링",
    "aggregates": "집계합니다", "aggregated": "집계된", "aggregation": "집계",
    "summarizes": "요약합니다", "summarized": "요약된", "summarization": "요약",
    "collects": "수집합니다", "collected": "수집된", "collection": "컬렉션",
    "gathers": "수집합니다", "gathered": "수집된", "gathering": "수집",
    "accumulates": "축적합니다", "accumulated": "축적된", "accumulation": "축적",
    "compiles": "컴파일합니다", "compiled": "컴파일된", "compilation": "컴파일",
    "assembles": "조립합니다", "assembled": "조립된", "assembly": "조립",
    "packages": "패키징합니다", "packaged": "패키징된", "packaging": "패키징",
    "bundles": "번들링합니다", "bundled": "번들링된", "bundling": "번들링",
    "wraps": "래핑합니다", "wrapped": "래핑된", "wrapping": "래핑",
    "encapsulates": "캡슐화합니다", "encapsulated": "캡슐화된", "encapsulation": "캡슐화",
    "abstracts": "추상화합니다", "abstracted": "추상화된", "abstraction": "추상화",
    "interfaces": "인터페이스합니다", "interfaced": "인터페이스된",
    "exposes": "노출합니다", "exposed": "노출된", "exposing": "노출하는",
    "hides": "숨깁니다", "hidden": "숨겨진", "hiding": "숨기는",
    "masks": "마스킹합니다", "masked": "마스킹된", "masking": "마스킹",
    "obfuscates": "난독화합니다", "obfuscated": "난독화된", "obfuscation": "난독화",
    "encrypts": "암호화합니다", "encrypted": "암호화된", "encryption": "암호화",
    "decrypts": "복호화합니다", "decrypted": "복호화된", "decryption": "복호화",
    "hashes": "해시합니다", "hashed": "해시된", "hashing": "해싱",
    "signs": "서명합니다", "signed": "서명된", "signing": "서명",
    "authenticates": "인증합니다", "authenticated": "인증된", "authentication": "인증",
    "authorizes": "인가합니다", "authorized": "인가된", "authorization": "인가",
    "grants": "부여합니다", "granted": "부여된", "granting": "부여하는",
    "denies": "거부합니다", "denied": "거부된", "denying": "거부하는",
    "allows": "허용합니다", "allowed": "허용된", "allowing": "허용하는",
    "permits": "허가합니다", "permitted": "허가된", "permission": "권한", "permissions": "권한",
    "forbids": "금지합니다", "forbidden": "금지된", "forbidding": "금지하는",
    "blocks": "차단합니다", "blocked": "차단된",
    "throttles": "제한합니다", "throttled": "제한된", "throttling": "제한",
    "rate-limits": "속도 제한합니다", "rate-limited": "속도 제한된", "rate limiting": "속도 제한",
    "queues": "대기열에 넣습니다", "queued": "대기열에 있는",
    "buffers": "버퍼링합니다", "buffered": "버퍼링된", "buffering": "버퍼링",
    "streams": "스트리밍합니다", "streamed": "스트리밍된", "streaming": "스트리밍",
    "pipes": "파이핑합니다", "piped": "파이핑된", "piping": "파이핑",
    "flows": "흐릅니다", "flowed": "흐른", "flowing": "흐르는",
    "propagates": "전파합니다", "propagated": "전파된", "propagation": "전파",
    "cascades": "계단식으로 전파합니다", "cascaded": "계단식 전파된", "cascading": "계단식 전파",
    "triggers": "트리거합니다", "triggered": "트리거된", "triggering": "트리거하는",
    "emits": "방출합니다", "emitted": "방출된", "emitting": "방출하는", "emission": "방출",
    "broadcasts": "브로드캐스트합니다", "broadcasted": "브로드캐스트된", "broadcasting": "브로드캐스트",
    "multicasts": "멀티캐스트합니다", "multicasted": "멀티캐스트된", "multicasting": "멀티캐스트",
    "unicasts": "유니캐스트합니다", "unicasted": "유니캐스트된", "unicasting": "유니캐스트",
    "notifies": "알립니다", "notified": "알림받은", "notification": "알림", "notifications": "알림",
    "alerts": "경고합니다", "alerted": "경고된", "alerting": "경고",
    "warns": "경고합니다", "warned": "경고된", "warning": "경고",
    "signals": "신호합니다", "signaled": "신호된", "signaling": "신호",
    "indicates": "나타냅니다", "indicated": "나타낸", "indication": "표시",
    "suggests": "제안합니다", "suggested": "제안된", "suggestion": "제안",
    "recommends": "권장합니다", "recommended": "권장된", "recommendation": "권장사항",
    "advises": "조언합니다", "advised": "조언된", "advice": "조언",
    "guides": "안내합니다", "guided": "안내된", "guiding": "안내하는", "guide": "가이드",
    "directs": "안내합니다", "directed": "안내된",
    "assists": "지원합니다", "assisted": "지원된", "assistance": "지원",
    "helps": "돕습니다", "helped": "도움받은", "helping": "돕는",
    "supports": "지원합니다", "supported": "지원된", "support": "지원",
    "facilitates": "촉진합니다", "facilitated": "촉진된", "facilitation": "촉진",
    "enables": "가능하게 합니다", "enabled": "활성화된", "enabling": "가능하게 하는",
    "empowers": "권한을 부여합니다", "empowered": "권한이 부여된",
    "strengthens": "강화합니다", "strengthened": "강화된", "strengthening": "강화하는",
    "reinforces": "강화합니다", "reinforced": "강화된", "reinforcement": "강화",
    "fortifies": "강화합니다", "fortified": "강화된",
    "hardens": "강화합니다", "hardened": "강화된", "hardening": "강화",
    "toughens": "강화합니다", "toughened": "강화된",
    "stabilizes": "안정화합니다", "stabilized": "안정화된", "stabilization": "안정화",
    "normalizes": "정규화합니다", "normalized": "정규화된", "normalization": "정규화",
    "standardizes": "표준화합니다", "standardized": "표준화된", "standardization": "표준화",
    "unifies": "통합합니다", "unified": "통합된", "unification": "통합",
    "consolidates": "통합합니다", "consolidated": "통합된", "consolidation": "통합",
    "centralizes": "중앙 집중화합니다", "centralized": "중앙 집중화된", "centralization": "중앙 집중화",
    "decentralizes": "분산합니다", "decentralized": "분산된", "decentralization": "분산화",
    "federates": "연합합니다", "federated": "연합된", "federation": "연합",
    "isolates": "격리합니다", "isolated": "격리된", "isolation": "격리",
    "separates": "분리합니다", "separated": "분리된", "separation": "분리",
    "divides": "나눕니다", "divided": "나뉜", "dividing": "나누는", "division": "분할",
    "splits": "분할합니다", "split": "분할된", "splitting": "분할하는",
    "segments": "세그먼트합니다", "segmented": "세그먼트된", "segmentation": "세그먼테이션",
    "fragments": "조각냅니다", "fragmented": "조각난", "fragmentation": "단편화",
    "decomposes": "분해합니다", "decomposed": "분해된", "decomposition": "분해",
    "breaks down": "분해합니다", "broken down": "분해된",
    "dismantles": "해체합니다", "dismantled": "해체된",
    "disassembles": "분해합니다", "disassembled": "분해된", "disassembly": "분해",
    "unpacks": "압축을 풉니다", "unpacked": "압축 해제된", "unpacking": "압축 해제",
    "extracts": "추출합니다", "extracted": "추출된", "extraction": "추출",
    "parses": "파싱합니다", "parsed": "파싱된", "parsing": "파싱",
    "tokenizes": "토큰화합니다", "tokenized": "토큰화된", "tokenization": "토큰화",
    "serializes": "직렬화합니다", "serialized": "직렬화된", "serialization": "직렬화",
    "deserializes": "역직렬화합니다", "deserialized": "역직렬화된", "deserialization": "역직렬화",
    "marshals": "마샬링합니다", "marshaled": "마샬링된", "marshaling": "마샬링",
    "unmarshals": "언마샬링합니다", "unmarshaled": "언마샬링된", "unmarshaling": "언마샬링",
    "encodes": "인코딩합니다", "encoded": "인코딩된", "encoding": "인코딩",
    "decodes": "디코딩합니다", "decoded": "디코딩된", "decoding": "디코딩",
    "compresses": "압축합니다", "compressed": "압축된", "compression": "압축",
    "decompresses": "압축 해제합니다", "decompressed": "압축 해제된", "decompression": "압축 해제",
    "zips": "압축합니다", "zipped": "압축된", "zipping": "압축",
    "unzips": "압축 해제합니다", "unzipped": "압축 해제된", "unzipping": "압축 해제",
    "archives": "아카이브합니다", "archived": "아카이브된", "archiving": "아카이빙", "archive": "아카이브",
    "unarchives": "아카이브 해제합니다", "unarchived": "아카이브 해제된",
    "indexes": "색인합니다", "indexed": "색인된", "indexing": "색인",
    "catalogs": "카탈로그화합니다", "cataloged": "카탈로그화된", "cataloging": "카탈로그화",
    "inventories": "목록화합니다", "inventoried": "목록화된",
    "lists": "나열합니다", "listed": "나열된", "listing": "목록",
    "enumerates": "열거합니다", "enumerated": "열거된", "enumeration": "열거",
    "counts": "계산합니다", "counted": "계산된", "counting": "계산",
    "tallies": "집계합니다", "tallied": "집계된",
    "sums": "합계합니다", "summed": "합계된", "summing": "합계",
    "totals": "합계합니다", "totaled": "합계된",
    "averages": "평균합니다", "averaged": "평균된", "averaging": "평균",
    "weights": "가중치를 부여합니다", "weighted": "가중치가 부여된", "weighting": "가중치 부여",
    "scores": "점수를 매깁니다", "scored": "점수가 매겨진", "scoring": "점수 매기기",
    "ranks": "순위를 매깁니다", "ranked": "순위가 매겨진", "ranking": "순위",
    "rates": "평가합니다", "rated": "평가된", "rating": "등급",
    "prioritizes": "우선순위를 정합니다", "prioritized": "우선순위가 정해진", "prioritization": "우선순위 지정",
    "orders": "정렬합니다", "ordered": "정렬된", "ordering": "정렬",
    "sorts": "정렬합니다", "sorted": "정렬된", "sorting": "정렬",
    "arranges": "배열합니다", "arranged": "배열된",
    "sequences": "순서를 정합니다", "sequenced": "순서가 정해진", "sequencing": "순서 지정",
    "aligns": "정렬합니다", "aligned": "정렬된", "aligning": "정렬하는", "alignment": "정렬",
    "matches": "일치합니다", "matched": "일치된", "matching": "일치하는",
    "compares": "비교합니다", "compared": "비교된", "comparison": "비교",
    "contrasts": "대조합니다", "contrasted": "대조된",
    "differentiates": "구별합니다", "differentiated": "구별된", "differentiation": "구별",
    "distinguishes": "구분합니다", "distinguished": "구분된",
    "discriminates": "식별합니다", "discriminated": "식별된", "discrimination": "식별",
    "categorizes": "분류합니다", "categorized": "분류된", "categorization": "분류",
    "classifies": "분류합니다", "classified": "분류된", "classification": "분류",
    "tags": "태그합니다", "tagged": "태그된", "tagging": "태깅",
    "labels": "라벨링합니다", "labeled": "라벨링된", "labeling": "라벨링",
    "annotates": "주석을 답니다", "annotated": "주석이 달린", "annotation": "주석",
    "marks": "표시합니다", "marked": "표시된", "marking": "표시",
    "highlights": "강조합니다", "highlighted": "강조된", "highlighting": "강조",
    "emphasizes": "강조합니다", "emphasized": "강조된",
    "stresses": "강조합니다", "stressed": "강조된",
    "underlines": "밑줄 긋습니다", "underlined": "밑줄 그어진",
    "italicizes": "기울임꼴로 합니다", "italicized": "기울임꼴인",
    "bolds": "굵게 합니다", "bolded": "굵은",
    "formats": "형식을 지정합니다", "formatted": "형식이 지정된", "formatting": "형식 지정",
    "styles": "스타일을 지정합니다", "styled": "스타일이 지정된", "styling": "스타일 지정",
    "themes": "테마를 지정합니다", "themed": "테마가 지정된", "theming": "테마 지정",
    "customizes": "사용자 정의합니다", "customized": "사용자 정의된",
    "tailors": "맞춤 설정합니다", "tailored": "맞춤 설정된", "tailoring": "맞춤 설정",
    
    # Common nouns
    "feature": "기능", "features": "기능",
    "capability": "역량", "capabilities": "역량",
    "function": "함수", "functions": "함수",
    "method": "메서드", "methods": "메서드",
    "procedure": "절차", "procedures": "절차",
    "process": "프로세스", "processes": "프로세스",
    "workflow": "워크플로우", "workflows": "워크플로우",
    "pipeline": "파이프라인", "pipelines": "파이프라인",
    "pattern": "패턴", "patterns": "패턴",
    "architecture": "아키텍처", "architectures": "아키텍처",
    "design": "설계", "designs": "설계",
    "structure": "구조", "structures": "구조",
    "framework": "프레임워크", "frameworks": "프레임워크",
    "platform": "플랫폼", "platforms": "플랫폼",
    "system": "시스템", "systems": "시스템",
    "service": "서비스", "services": "서비스",
    "application": "애플리케이션", "applications": "애플리케이션",
    "program": "프로그램", "programs": "프로그램",
    "software": "소프트웨어",
    "hardware": "하드웨어",
    "infrastructure": "인프라",
    "environment": "환경", "environments": "환경",
    "runtime": "런타임",
    "container": "컨테이너", "containers": "컨테이너",
    "cluster": "클러스터", "clusters": "클러스터",
    "node": "노드", "nodes": "노드",
    "instance": "인스턴스", "instances": "인스턴스",
    "server": "서버", "servers": "서버",
    "client": "클라이언트", "clients": "클라이언트",
    "endpoint": "엔드포인트", "endpoints": "엔드포인트",
    "interface": "인터페이스", "interfaces": "인터페이스",
    "contract": "계약", "contracts": "계약",
    "schema": "스키마", "schemas": "스키마",
    "model": "모델", "models": "모델",
    "entity": "엔터티", "entities": "엔터티",
    "object": "객체", "objects": "객체",
    "class": "클래스", "classes": "클래스",
    "type": "유형", "types": "유형",
    "component": "컴포넌트", "components": "컴포넌트",
    "module": "모듈", "modules": "모듈",
    "package": "패키지", "packages": "패키지",
    "library": "라이브러리", "libraries": "라이브러리",
    "dependency": "종속성", "dependencies": "종속성",
    "resource": "리소스", "resources": "리소스",
    "asset": "자산", "assets": "자산",
    "file": "파일", "files": "파일",
    "folder": "폴더", "folders": "폴더",
    "directory": "디렉터리", "directories": "디렉터리",
    "path": "경로", "paths": "경로",
    "location": "위치", "locations": "위치",
    "address": "주소", "addresses": "주소",
    "reference": "참조", "references": "참조",
    "pointer": "포인터", "pointers": "포인터",
    "link": "링크", "links": "링크",
    "connection": "연결", "connections": "연결",
    "relationship": "관계", "relationships": "관계",
    "association": "연관", "associations": "연관",
    "binding": "바인딩", "bindings": "바인딩",
    "mapping": "매핑", "mappings": "매핑",
    "route": "라우트", "routes": "라우트",
    "router": "라우터", "routers": "라우터",
    "handler": "핸들러", "handlers": "핸들러",
    "controller": "컨트롤러", "controllers": "컨트롤러",
    "view": "뷰", "views": "뷰",
    "template": "템플릿", "templates": "템플릿",
    "layout": "레이아웃", "layouts": "레이아웃",
    "page": "페이지", "pages": "페이지",
    "screen": "화면", "screens": "화면",
    "form": "폼", "forms": "폼",
    "field": "필드", "fields": "필드",
    "input": "입력", "inputs": "입력",
    "output": "출력", "outputs": "출력",
    "parameter": "매개변수", "parameters": "매개변수",
    "argument": "인수", "arguments": "인수",
    "value": "값", "values": "값",
    "variable": "변수", "variables": "변수",
    "constant": "상수", "constants": "상수",
    "property": "속성", "properties": "속성",
    "attribute": "속성", "attributes": "속성",
    "key": "키", "keys": "키",
    "pair": "쌍", "pairs": "쌍",
    "tuple": "튜플", "tuples": "튜플",
    "list": "목록", "lists": "목록",
    "array": "배열", "arrays": "배열",
    "set": "세트", "sets": "세트",
    "map": "맵", "maps": "맵",
    "dictionary": "딕셔너리", "dictionaries": "딕셔너리",
    "hash": "해시", "hashes": "해시",
    "table": "테이블", "tables": "테이블",
    "index": "인덱스", "indexes": "인덱스", "indices": "인덱스",
    "record": "레코드", "records": "레코드",
    "row": "행", "rows": "행",
    "column": "열", "columns": "열",
    "cell": "셀", "cells": "셀",
    "query": "쿼리", "queries": "쿼리",
    "request": "요청", "requests": "요청",
    "response": "응답", "responses": "응답",
    "message": "메시지", "messages": "메시지",
    "event": "이벤트", "events": "이벤트",
    "signal": "신호", "signals": "신호",
    "notification": "알림", "notifications": "알림",
    "alert": "경고", "alerts": "경고",
    "warning": "경고", "warnings": "경고",
    "error": "오류", "errors": "오류",
    "exception": "예외", "exceptions": "예외",
    "fault": "결함", "faults": "결함",
    "failure": "실패", "failures": "실패",
    "issue": "이슈", "issues": "이슈",
    "problem": "문제", "problems": "문제",
    "bug": "버그", "bugs": "버그",
    "defect": "결함", "defects": "결함",
    "flaw": "결점", "flaws": "결점",
    "vulnerability": "취약점", "vulnerabilities": "취약점",
    "threat": "위협", "threats": "위협",
    "risk": "위험", "risks": "위험",
    "attack": "공격", "attacks": "공격",
    "breach": "침해", "breaches": "침해",
    "violation": "위반", "violations": "위반",
    "exploit": "익스플로잇", "exploits": "익스플로잇",
    "injection": "인젝션", "injections": "인젝션",
    "payload": "페이로드", "payloads": "페이로드",
    "malware": "악성코드",
    "virus": "바이러스", "viruses": "바이러스",
    "trojan": "트로이목마", "trojans": "트로이목마",
    "worm": "웜", "worms": "웜",
    "ransomware": "랜섬웨어",
    "spyware": "스파이웨어",
    "adware": "애드웨어",
    "phishing": "피싱",
    "spam": "스팸",
    "bot": "봇", "bots": "봇",
    "crawler": "크롤러", "crawlers": "크롤러",
    "spider": "스파이더", "spiders": "스파이더",
    "scraper": "스크래퍼", "scrapers": "스크래퍼",
    "agent": "에이전트", "agents": "에이전트",
    "actor": "액터", "actors": "액터",
    "user": "사용자", "users": "사용자",
    "account": "계정", "accounts": "계정",
    "profile": "프로필", "profiles": "프로필",
    "identity": "아이덴티티", "identities": "아이덴티티",
    "credential": "자격 증명", "credentials": "자격 증명",
    "token": "토큰", "tokens": "토큰",
    "session": "세션", "sessions": "세션",
    "cookie": "쿠키", "cookies": "쿠키",
    "header": "헤더", "headers": "헤더",
    "footer": "푸터", "footers": "푸터",
    "body": "본문", "bodies": "본문",
    "content": "콘텐츠", "contents": "콘텐츠",
    "data": "데이터",
    "information": "정보",
    "knowledge": "지식",
    "insight": "인사이트", "insights": "인사이트",
    "analytics": "분석",
    "metrics": "메트릭",
    "statistics": "통계",
    "report": "보고서", "reports": "보고서",
    "dashboard": "대시보드", "dashboards": "대시보드",
    "chart": "차트", "charts": "차트",
    "graph": "그래프", "graphs": "그래프",
    "diagram": "다이어그램", "diagrams": "다이어그램",
    "visualization": "시각화", "visualizations": "시각화",
    "display": "디스플레이", "displays": "디스플레이",
    "presentation": "프레젠테이션", "presentations": "프레젠테이션",
    "demo": "데모", "demos": "데모",
    "example": "예제", "examples": "예제",
    "sample": "샘플", "samples": "샘플",
    "specimen": "표본", "specimens": "표본",
    "prototype": "프로토타입", "prototypes": "프로토타입",
    "mockup": "목업", "mockups": "목업",
    "wireframe": "와이어프레임", "wireframes": "와이어프레임",
    "sketch": "스케치", "sketches": "스케치",
    "draft": "초안", "drafts": "초안",
    "version": "버전", "versions": "버전",
    "revision": "수정본", "revisions": "수정본",
    "iteration": "반복", "iterations": "반복",
    "release": "릴리스", "releases": "릴리스",
    "build": "빌드", "builds": "빌드",
    "artifact": "아티팩트", "artifacts": "아티팩트",
    "binary": "바이너리", "binaries": "바이너리",
    "executable": "실행 파일", "executables": "실행 파일",
    "source": "소스",
    "code": "코드",
    "script": "스크립트", "scripts": "스크립트",
    "command": "명령", "commands": "명령",
    "instruction": "지시", "instructions": "지시사항",
    "directive": "지시문", "directives": "지시문",
    "rule": "규칙", "rules": "규칙",
    "policy": "정책", "policies": "정책",
    "guideline": "가이드라인", "guidelines": "가이드라인",
    "standard": "표준", "standards": "표준",
    "specification": "사양", "specifications": "사양",
    "protocol": "프로토콜", "protocols": "프로토콜",
    "convention": "규약", "conventions": "규약",
    "practice": "관행", "practices": "관행",
    "principle": "원칙", "principles": "원칙",
    "concept": "개념", "concepts": "개념",
    "idea": "아이디어", "ideas": "아이디어",
    "notion": "개념", "notions": "개념",
    "theory": "이론", "theories": "이론",
    "hypothesis": "가설", "hypotheses": "가설",
    "assumption": "가정", "assumptions": "가정",
    "premise": "전제", "premises": "전제",
    "foundation": "기반", "foundations": "기반",
    "basis": "기초", "bases": "기초",
    "core": "핵심",
    "essence": "본질",
    "fundamental": "기본",
    "basic": "기본",
    "elementary": "기초",
    "introductory": "입문",
    "beginner": "초보자",
    "novice": "초심자",
    "intermediate": "중급",
    "advanced": "고급",
    "expert": "전문가",
    "master": "마스터",
    "professional": "전문가",
    "specialist": "전문가",
    "consultant": "컨설턴트",
    "advisor": "어드바이저",
    "mentor": "멘토",
    "coach": "코치",
    "trainer": "트레이너",
    "instructor": "강사",
    "teacher": "교사",
    "educator": "교육자",
    "professor": "교수",
    "researcher": "연구원",
    "scientist": "과학자",
    "engineer": "엔지니어",
    "developer": "개발자",
    "programmer": "프로그래머",
    "coder": "코더",
    "architect": "아키텍트",
    "designer": "디자이너",
    "analyst": "분석가",
    "tester": "테스터",
    "reviewer": "리뷰어",
    "auditor": "감사자",
    "administrator": "관리자",
    "operator": "운영자",
    "maintainer": "유지보수 담당자",
    "contributor": "기여자",
    "collaborator": "협력자",
    "partner": "파트너",
    "stakeholder": "이해관계자",
    "customer": "고객",
    "consumer": "소비자",
    "end user": "최종 사용자",
    "audience": "대상",
    "visitor": "방문자",
    "guest": "게스트",
    "member": "멤버",
    "team": "팀",
    "group": "그룹",
    "organization": "조직",
    "company": "회사",
    "enterprise": "기업",
    "business": "비즈니스",
    "industry": "산업",
    "sector": "섹터",
    "domain": "도메인",
    "field": "분야",
    "area": "영역",
    "scope": "범위",
    "context": "컨텍스트",
    "situation": "상황",
    "scenario": "시나리오",
    "case": "사례",
    "instance": "인스턴스",
    "occurrence": "발생",
    "incident": "인시던트",
    "event": "이벤트",
    "happening": "발생",
    "occasion": "경우",
    "circumstance": "상황",
    "condition": "조건",
    "state": "상태",
    "status": "상태",
    "stage": "단계",
    "phase": "단계",
    "step": "단계",
    "level": "레벨",
    "tier": "티어",
    "layer": "레이어",
    "dimension": "차원",
    "aspect": "측면",
    "facet": "측면",
    "perspective": "관점",
    "viewpoint": "관점",
    "angle": "각도",
    "approach": "접근법",
    "strategy": "전략",
    "tactic": "전술",
    "technique": "기법",
    "mechanism": "메커니즘",
    "algorithm": "알고리즘",
    "formula": "공식",
    "equation": "방정식",
    "calculation": "계산",
    "computation": "계산",
    "operation": "연산",
    "function": "함수",
    "expression": "표현식",
    "statement": "문",
    "declaration": "선언",
    "definition": "정의",
    "assignment": "할당",
    "initialization": "초기화",
    "invocation": "호출",
    "call": "호출",
    "return": "반환",
    "yield": "yield",
    "throw": "throw",
    "catch": "catch",
    "finally": "finally",
    "try": "try",
    "if": "if",
    "else": "else",
    "switch": "switch",
    "case": "case",
    "default": "default",
    "for": "for",
    "while": "while",
    "do": "do",
    "loop": "루프",
    "iteration": "반복",
    "recursion": "재귀",
    "callback": "콜백",
    "promise": "프로미스",
    "async": "비동기",
    "await": "await",
    "sync": "동기",
    "thread": "스레드",
    "coroutine": "코루틴",
    "fiber": "파이버",
    "goroutine": "고루틴",
    "task": "작업",
    "job": "작업",
    "worker": "워커",
    "executor": "실행기",
    "scheduler": "스케줄러",
    "dispatcher": "디스패처",
    "queue": "큐",
    "stack": "스택",
    "heap": "힙",
    "pool": "풀",
    "buffer": "버퍼",
    "cache": "캐시",
    "memory": "메모리",
    "storage": "스토리지",
    "disk": "디스크",
    "drive": "드라이브",
    "volume": "볼륨",
    "partition": "파티션",
    "database": "데이터베이스",
    "datastore": "데이터 스토어",
    "repository": "저장소",
    "warehouse": "웨어하우스",
    "lake": "레이크",
    "mart": "마트",
    "dimension": "차원",
    "fact": "팩트",
    "cube": "큐브",
    "aggregation": "집계",
    "rollup": "롤업",
    "drilldown": "드릴다운",
    "slice": "슬라이스",
    "dice": "다이스",
    "pivot": "피벗",
    "transaction": "트랜잭션",
    "commit": "커밋",
    "rollback": "롤백",
    "savepoint": "세이브포인트",
    "lock": "잠금",
    "unlock": "잠금 해제",
    "semaphore": "세마포어",
    "mutex": "뮤텍스",
    "barrier": "배리어",
    "fence": "펜스",
    "guard": "가드",
    "monitor": "모니터",
    "observer": "옵저버",
    "listener": "리스너",
    "watcher": "와처",
    "subscriber": "구독자",
    "publisher": "게시자",
    "producer": "프로듀서",
    "consumer": "컨슈머",
    "broker": "브로커",
    "mediator": "중재자",
    "proxy": "프록시",
    "gateway": "게이트웨이",
    "bridge": "브리지",
    "adapter": "어댑터",
    "wrapper": "래퍼",
    "facade": "파사드",
    "decorator": "데코레이터",
    "interceptor": "인터셉터",
    "middleware": "미들웨어",
    "filter": "필터",
    "validator": "검증기",
    "sanitizer": "새니타이저",
    "normalizer": "정규화기",
    "transformer": "변환기",
    "converter": "변환기",
    "parser": "파서",
    "lexer": "렉서",
    "tokenizer": "토크나이저",
    "compiler": "컴파일러",
    "interpreter": "인터프리터",
    "transpiler": "트랜스파일러",
    "bundler": "번들러",
    "loader": "로더",
    "resolver": "리졸버",
    "linker": "링커",
    "optimizer": "최적화기",
    "minifier": "미니파이어",
    "uglifier": "어글리파이어",
    "obfuscator": "난독화기",
    "linter": "린터",
    "formatter": "포매터",
    "beautifier": "뷰티파이어",
    "checker": "체커",
    "analyzer": "분석기",
    "profiler": "프로파일러",
    "tracer": "트레이서",
    "debugger": "디버거",
    "inspector": "인스펙터",
    "explorer": "탐색기",
    "viewer": "뷰어",
    "editor": "편집기",
    "builder": "빌더",
    "generator": "생성기",
    "creator": "생성기",
    "factory": "팩토리",
    "provider": "프로바이더",
    "supplier": "서플라이어",
    "injector": "인젝터",
    "container": "컨테이너",
    "registry": "레지스트리",
    "catalog": "카탈로그",
    "inventory": "인벤토리",
    "manifest": "매니페스트",
    "descriptor": "디스크립터",
    "metadata": "메타데이터",
    "annotation": "주석",
    "comment": "주석",
    "note": "노트",
    "remark": "비고",
    "description": "설명",
    "explanation": "설명",
    "clarification": "명확화",
    "interpretation": "해석",
    "translation": "번역",
    "localization": "로컬라이제이션",
    "internationalization": "국제화",
    "globalization": "글로벌화",
    "accessibility": "접근성",
    "usability": "사용성",
    "readability": "가독성",
    "maintainability": "유지보수성",
    "testability": "테스트 가능성",
    "reliability": "신뢰성",
    "availability": "가용성",
    "durability": "내구성",
    "resilience": "복원력",
    "robustness": "견고성",
    "stability": "안정성",
    "consistency": "일관성",
    "coherence": "일관성",
    "integrity": "무결성",
    "validity": "유효성",
    "accuracy": "정확성",
    "precision": "정밀도",
    "correctness": "정확성",
    "completeness": "완전성",
    "thoroughness": "철저함",
    "quality": "품질",
    "excellence": "우수성",
    "superiority": "우월성",
    "efficiency": "효율성",
    "effectiveness": "효과성",
    "productivity": "생산성",
    "performance": "성능",
    "speed": "속도",
    "throughput": "처리량",
    "latency": "지연 시간",
    "response time": "응답 시간",
    "turnaround": "처리 시간",
    "bandwidth": "대역폭",
    "capacity": "용량",
    "utilization": "사용률",
    "saturation": "포화",
    "bottleneck": "병목",
    "constraint": "제약",
    "limitation": "제한",
    "restriction": "제한",
    "boundary": "경계",
    "edge": "엣지",
    "margin": "마진",
    "padding": "패딩",
    "spacing": "간격",
    "gap": "간격",
    "offset": "오프셋",
    "indent": "들여쓰기",
    "alignment": "정렬",
    "justification": "정렬",
    "orientation": "방향",
    "direction": "방향",
    "order": "순서",
    "sequence": "시퀀스",
    "series": "시리즈",
    "progression": "진행",
    "flow": "흐름",
    "stream": "스트림",
    "pipeline": "파이프라인",
    "channel": "채널",
    "conduit": "통로",
    "pathway": "경로",
    "circuit": "회로",
    "loop": "루프",
    "cycle": "사이클",
    "period": "기간",
    "interval": "간격",
    "duration": "기간",
    "timeout": "타임아웃",
    "deadline": "데드라인",
    "timestamp": "타임스탬프",
    "datetime": "날짜시간",
    "date": "날짜",
    "time": "시간",
    "moment": "시점",
    "instant": "순간",
    "epoch": "에포크",
    "era": "시대",
    "generation": "세대",
    "legacy": "레거시",
    "heritage": "유산",
    "tradition": "전통",
    "convention": "규약",
    "custom": "사용자 정의",
    "habit": "습관",
    "routine": "루틴",
    "ritual": "의례",
    "ceremony": "의식",
    "protocol": "프로토콜",
    "etiquette": "에티켓",
    "manner": "방식",
    "style": "스타일",
    "flavor": "flavor",
    "variant": "변형",
    "dialect": "방언",
    "syntax": "구문",
    "grammar": "문법",
    "semantics": "의미론",
    "pragmatics": "화용론",
    "lexicon": "어휘",
    "vocabulary": "어휘",
    "terminology": "용어",
    "nomenclature": "명명법",
    "taxonomy": "분류법",
    "hierarchy": "계층",
    "tree": "트리",
    "graph": "그래프",
    "network": "네트워크",
    "mesh": "메시",
    "grid": "그리드",
    "matrix": "매트릭스",
    "lattice": "격자",
    "topology": "토폴로지",
    "geography": "지리",
    "landscape": "환경",
    "terrain": "지형",
    "ecosystem": "생태계",
    "biosphere": "생물권",
    "universe": "우주",
    "world": "세계",
    "realm": "영역",
    "sphere": "영역",
    "space": "공간",
    "dimension": "차원",
    "plane": "평면",
    "axis": "축",
    "coordinate": "좌표",
    "position": "위치",
    "location": "위치",
    "place": "장소",
    "site": "사이트",
    "spot": "지점",
    "point": "포인트",
    "mark": "마크",
    "marker": "마커",
    "indicator": "지표",
    "gauge": "게이지",
    "meter": "미터",
    "measure": "측정",
    "unit": "단위",
    "quantity": "수량",
    "amount": "양",
    "number": "숫자",
    "count": "개수",
    "total": "총계",
    "sum": "합계",
    "aggregate": "집계",
    "average": "평균",
    "mean": "평균",
    "median": "중앙값",
    "mode": "최빈값",
    "range": "범위",
    "spread": "분산",
    "deviation": "편차",
    "variance": "분산",
    "standard deviation": "표준 편차",
    "percentile": "백분위수",
    "quartile": "사분위수",
    "decile": "십분위수",
    "quintile": "오분위수",
    "ratio": "비율",
    "proportion": "비율",
    "percentage": "백분율",
    "fraction": "분수",
    "decimal": "십진수",
    "float": "부동소수점",
    "integer": "정수",
    "whole number": "정수",
    "natural number": "자연수",
    "prime": "소수",
    "composite": "합성수",
    "factor": "인수",
    "multiple": "배수",
    "dividend": "피제수",
    "divisor": "제수",
    "quotient": "몫",
    "remainder": "나머지",
    "modulo": "나머지",
    "exponent": "지수",
    "power": "거듭제곱",
    "base": "밑",
    "logarithm": "로그",
    "root": "근",
    "square root": "제곱근",
    "cube root": "세제곱근",
    
    # Common adjectives
    "new": "새로운",
    "old": "오래된",
    "current": "현재",
    "previous": "이전",
    "next": "다음",
    "last": "마지막",
    "first": "첫 번째",
    "initial": "초기",
    "final": "최종",
    "latest": "최신",
    "recent": "최근",
    "upcoming": "다가오는",
    "future": "미래",
    "past": "과거",
    "present": "현재",
    "existing": "기존",
    "legacy": "레거시",
    "modern": "현대적인",
    "contemporary": "현대",
    "traditional": "전통적인",
    "conventional": "기존",
    "classic": "클래식",
    "standard": "표준",
    "typical": "일반적인",
    "common": "일반적인",
    "usual": "일반적인",
    "normal": "정상",
    "regular": "일반",
    "ordinary": "평범한",
    "average": "평균",
    "general": "일반",
    "generic": "일반",
    "universal": "범용",
    "global": "전역",
    "local": "로컬",
    "regional": "지역",
    "specific": "특정",
    "particular": "특정",
    "individual": "개별",
    "unique": "고유한",
    "distinct": "구별되는",
    "different": "다른",
    "separate": "별도",
    "independent": "독립적인",
    "standalone": "독립 실행형",
    "isolated": "격리된",
    "decoupled": "분리된",
    "coupled": "결합된",
    "integrated": "통합된",
    "unified": "통합된",
    "combined": "결합된",
    "merged": "병합된",
    "mixed": "혼합된",
    "hybrid": "하이브리드",
    "composite": "복합",
    "complex": "복잡한",
    "complicated": "복잡한",
    "intricate": "복잡한",
    "sophisticated": "정교한",
    "elaborate": "정교한",
    "detailed": "상세한",
    "comprehensive": "포괄적인",
    "extensive": "광범위한",
    "broad": "넓은",
    "wide": "넓은",
    "narrow": "좁은",
    "limited": "제한된",
    "restricted": "제한된",
    "constrained": "제약된",
    "bounded": "제한된",
    "unlimited": "무제한",
    "unrestricted": "제한 없는",
    "infinite": "무한",
    "finite": "유한",
    "complete": "완전한",
    "partial": "부분",
    "full": "전체",
    "empty": "빈",
    "filled": "채워진",
    "populated": "채워진",
    "vacant": "비어 있는",
    "available": "사용 가능한",
    "unavailable": "사용 불가능한",
    "accessible": "접근 가능한",
    "inaccessible": "접근 불가능한",
    "reachable": "도달 가능한",
    "unreachable": "도달 불가능한",
    "visible": "표시되는",
    "invisible": "숨겨진",
    "hidden": "숨겨진",
    "exposed": "노출된",
    "public": "공개",
    "private": "비공개",
    "protected": "보호된",
    "internal": "내부",
    "external": "외부",
    "inner": "내부",
    "outer": "외부",
    "inside": "��부",
    "outside": "외부",
    "inbound": "인바운드",
    "outbound": "아웃바운드",
    "incoming": "들어오는",
    "outgoing": "나가는",
    "upstream": "업스트림",
    "downstream": "다운스트림",
    "forward": "앞으로",
    "backward": "뒤로",
    "reverse": "역방향",
    "inverse": "역",
    "opposite": "반대",
    "contrary": "반대",
    "positive": "양수",
    "negative": "음수",
    "affirmative": "긍정",
    "negative": "부정",
    "true": "참",
    "false": "거짓",
    "valid": "유효한",
    "invalid": "유효하지 않은",
    "correct": "올바른",
    "incorrect": "올바르지 않은",
    "right": "맞는",
    "wrong": "틀린",
    "good": "좋은",
    "bad": "나쁜",
    "better": "더 나은",
    "worse": "더 나쁜",
    "best": "최선의",
    "worst": "최악의",
    "optimal": "최적",
    "suboptimal": "차선",
    "ideal": "이상적인",
    "perfect": "완벽한",
    "flawless": "결함 없는",
    "imperfect": "불완전한",
    "defective": "결함이 있는",
    "faulty": "결함이 있는",
    "broken": "고장난",
    "damaged": "손상된",
    "corrupted": "손상된",
    "intact": "손상되지 않은",
    "whole": "전체",
    "fractional": "일부",
    "complete": "완전한",
    "incomplete": "불완전한",
    "finished": "완료된",
    "unfinished": "미완료",
    "done": "완료",
    "undone": "실행 취소",
    "pending": "보류 중",
    "active": "활성",
    "inactive": "비활성",
    "enabled": "활성화됨",
    "disabled": "비활성화됨",
    "on": "켜짐",
    "off": "꺼짐",
    "running": "실행 중",
    "stopped": "중지됨",
    "paused": "일시 중지됨",
    "suspended": "일시 중단됨",
    "resumed": "재개됨",
    "started": "시작됨",
    "terminated": "종료됨",
    "completed": "완료됨",
    "cancelled": "취소됨",
    "aborted": "중단됨",
    "failed": "실패",
    "succeeded": "성공",
    "successful": "성공한",
    "unsuccessful": "실패한",
    "passed": "통과",
    "failed": "실패",
    "skipped": "건너뜀",
    "ignored": "무시됨",
    "pending": "대기 중",
    "queued": "대기열에 있음",
    "scheduled": "예약됨",
    "delayed": "지연됨",
    "deferred": "연기됨",
    "postponed": "연기됨",
    "expedited": "신속 처리됨",
    "prioritized": "우선순위가 지정됨",
    "deprioritized": "우선순위가 낮아짐",
    "urgent": "긴급",
    "critical": "긴급",
    "important": "중요한",
    "significant": "중요한",
    "major": "주요",
    "minor": "부수적",
    "trivial": "사소한",
    "negligible": "무시할 수 있는",
    "essential": "필수",
    "necessary": "필요한",
    "required": "필수",
    "mandatory": "필수",
    "optional": "선택적",
    "elective": "선택적",
    "discretionary": "재량",
    "voluntary": "자발적",
    "compulsory": "의무",
    "obligatory": "의무",
    "enforced": "시행됨",
    "recommended": "권장됨",
    "suggested": "제안됨",
    "advised": "권고됨",
    "preferred": "선호됨",
    "favored": "선호됨",
    "desired": "원하는",
    "wanted": "원하는",
    "needed": "필요한",
    "sought": "찾는",
    "expected": "예상되는",
    "anticipated": "예상되는",
    "predicted": "예측되는",
    "forecast": "예측",
    "projected": "예상",
    "estimated": "추정",
    "calculated": "계산된",
    "computed": "계산된",
    "determined": "결정된",
    "resolved": "해결된",
    "fixed": "수정됨",
    "repaired": "복구됨",
    "restored": "복원됨",
    "recovered": "복구됨",
    "salvaged": "복구됨",
    "rescued": "구조됨",
    "saved": "저장됨",
    "preserved": "보존됨",
    "maintained": "유지됨",
    "kept": "보관됨",
    "held": "보유됨",
    "retained": "보유됨",
    "stored": "저장됨",
    "cached": "캐시됨",
    "buffered": "버퍼됨",
    "queued": "대기열에 있음",
    "stacked": "스택됨",
    "pooled": "풀링됨",
    "batched": "배치됨",
    "grouped": "그룹화됨",
    "clustered": "클러스터링됨",
    "aggregated": "집계됨",
    "combined": "결합됨",
    "merged": "병합됨",
    "joined": "결합됨",
    "connected": "연결됨",
    "linked": "연결됨",
    "associated": "연관됨",
    "related": "관련됨",
    "relevant": "관련",
    "pertinent": "적절한",
    "applicable": "적용 가능한",
    "suitable": "적합한",
    "appropriate": "적절한",
    "proper": "적절한",
    "fit": "적합한",
    "matching": "일치하는",
    "compatible": "호환되는",
    "incompatible": "호환되지 않는",
    "consistent": "일관된",
    "inconsistent": "일관되지 않은",
    "coherent": "일관된",
    "incoherent": "일관되지 않은",
    "logical": "논리적인",
    "illogical": "비논리적인",
    "rational": "합리적인",
    "irrational": "비합리적인",
    "reasonable": "합리적인",
    "unreasonable": "비합리적인",
    "sensible": "합리적인",
    "nonsensical": "무의미한",
    "meaningful": "의미 있는",
    "meaningless": "무의미한",
    "significant": "중요한",
    "insignificant": "중요하지 않은",
    "substantial": "상당한",
    "insubstantial": "미미한",
    "considerable": "상당한",
    "negligible": "무시할 수 있는",
    "notable": "주목할 만한",
    "remarkable": "주목할 만한",
    "noteworthy": "주목할 만한",
    "outstanding": "뛰어난",
    "exceptional": "예외적인",
    "extraordinary": "특별한",
    "unusual": "특이한",
    "uncommon": "드문",
    "rare": "드문",
    "scarce": "드문",
    "abundant": "풍부한",
    "plentiful": "풍부한",
    "ample": "충분한",
    "sufficient": "충분한",
    "adequate": "적절한",
    "insufficient": "불충분한",
    "inadequate": "부적절한",
    "lacking": "부족한",
    "deficient": "부족한",
    "excessive": "과도한",
    "superfluous": "불필요한",
    "redundant": "중복된",
    "duplicate": "중복",
    "unique": "고유한",
    "singular": "단일",
    "multiple": "여러",
    "several": "여러",
    "numerous": "수많은",
    "many": "많은",
    "few": "적은",
    "some": "일부",
    "any": "어떤",
    "all": "모든",
    "every": "모든",
    "each": "각",
    "both": "둘 다",
    "either": "둘 중 하나",
    "neither": "둘 다 아님",
    "none": "없음",
    "no": "아니요",
    "yes": "예",
    "maybe": "아마도",
    "perhaps": "아마도",
    "possibly": "가능하게",
    "probably": "아마",
    "likely": "가능성이 높은",
    "unlikely": "가능성이 낮은",
    "certain": "확실한",
    "uncertain": "불확실한",
    "sure": "확실한",
    "unsure": "불확실한",
    "definite": "확정적인",
    "indefinite": "불확정적인",
    "clear": "명확한",
    "unclear": "불명확한",
    "obvious": "명백한",
    "obscure": "모호한",
    "evident": "명백한",
    "ambiguous": "애매한",
    "explicit": "명시적인",
    "implicit": "암시적인",
    "direct": "직접",
    "indirect": "간접",
    "straightforward": "간단한",
    "complicated": "복잡한",
    "simple": "간단한",
    "complex": "복잡한",
    "easy": "쉬운",
    "difficult": "어려운",
    "hard": "어려운",
    "challenging": "도전적인",
    "trivial": "사소한",
    "nontrivial": "비자명한",
    "basic": "기본",
    "advanced": "고급",
    "elementary": "기초",
    "sophisticated": "정교한",
    "primitive": "원시",
    "crude": "조잡한",
    "refined": "정제된",
    "polished": "다듬어진",
    "rough": "거친",
    "smooth": "부드러운",
    "coarse": "거친",
    "fine": "세밀한",
    "granular": "세분화된",
    "atomic": "원자적",
    "monolithic": "모놀리식",
    "modular": "모듈식",
    "component-based": "컴포넌트 기반",
    "service-oriented": "서비스 지향",
    "event-driven": "이벤트 기반",
    "data-driven": "데이터 기반",
    "test-driven": "테스트 주도",
    "behavior-driven": "행동 주도",
    "domain-driven": "도메인 주도",
    "contract-first": "계약 우선",
    "code-first": "코드 우선",
    "schema-first": "스키마 우선",
    "api-first": "API 우선",
    "mobile-first": "모바일 우선",
    "cloud-first": "클라우드 우선",
    "security-first": "보안 우선",
    "performance-first": "성능 우선",
    "quality-first": "품질 우선",
    "user-first": "사용자 우선",
    "customer-first": "고객 우선",
    "developer-friendly": "개발자 친화적인",
    "user-friendly": "사용자 친화적인",
    "production-ready": "프로덕션 준비 완료",
    "enterprise-ready": "엔터프라이즈 준비 완료",
    "battle-tested": "검증된",
    "proven": "입증된",
    "mature": "성숙한",
    "stable": "안정적인",
    "experimental": "실험적",
    "beta": "베타",
    "alpha": "알파",
    "preview": "미리보기",
    "deprecated": "더 이상 사용되지 않음",
    "obsolete": "구식",
    "outdated": "오래됨",
    "current": "현재",
    "up-to-date": "최신",
    "cutting-edge": "최첨단",
    "bleeding-edge": "최신",
    "state-of-the-art": "최첨단",
    "next-generation": "차세대",
    "future-proof": "미래 대비",
    "backward-compatible": "하위 호환",
    "forward-compatible": "상위 호환",
    "cross-platform": "크로스 플랫폼",
    "platform-agnostic": "플랫폼 독립적",
    "language-agnostic": "언어 독립적",
    "vendor-neutral": "벤더 중립적",
    "open-source": "오픈 소스",
    "closed-source": "클로즈드 소스",
    "proprietary": "독점",
    "commercial": "상업",
    "free": "무료",
    "paid": "유료",
    "premium": "프리미엄",
    "enterprise": "엔터프라이즈",
    "community": "커뮤니티",
    "professional": "프로페셔널",
    "personal": "개인",
    "team": "팀",
    "organization": "조직",
    "self-hosted": "자체 호스팅",
    "cloud-hosted": "클라우드 호스팅",
    "managed": "관리형",
    "unmanaged": "비관리형",
    "serverless": "서버리스",
    "containerized": "컨테이너화된",
    "virtualized": "가상화된",
    "bare-metal": "베어 메탈",
    "on-premises": "온프레미스",
    "hybrid": "하이브리드",
    "multi-cloud": "멀티 클라우드",
    "single-cloud": "단일 클라우드",
    "cloud-native": "클라우드 네이티브",
    "cloud-agnostic": "클라우드 독립적",
    "highly available": "고가용성",
    "fault-tolerant": "장애 허용",
    "disaster-resistant": "재해 복원",
    "geo-redundant": "지리적 이중화",
    "multi-region": "다중 리전",
    "single-region": "단일 리전",
    "multi-zone": "다중 존",
    "single-zone": "단일 존",
    "globally distributed": "전역 분산",
    "regionally distributed": "지역 분산",
    "centrally located": "중앙 위치",
    "edge-located": "엣지 위치",
    "latency-sensitive": "지연 시간에 민감한",
    "latency-tolerant": "지연 시간에 관대한",
    "bandwidth-intensive": "대역폭 집약적",
    "compute-intensive": "컴퓨팅 집약적",
    "memory-intensive": "메모리 집약적",
    "storage-intensive": "스토리지 집약적",
    "I/O-bound": "I/O 제한",
    "CPU-bound": "CPU 제한",
    "network-bound": "네트워크 제한",
    "disk-bound": "디스크 제한",
    "resource-constrained": "리소스 제한",
    "resource-intensive": "리소스 집약적",
    "lightweight": "경량",
    "heavyweight": "헤비급",
    "minimal": "최소",
    "comprehensive": "포괄적인",
    "full-featured": "완전한 기능",
    "feature-rich": "기능이 풍부한",
    "feature-complete": "기능이 완전한",
    "feature-limited": "기능이 제한된",
    "extensible": "확장 가능한",
    "pluggable": "플러그 가능한",
    "customizable": "사용자 정의 가능한",
    "configurable": "구성 가능한",
    "adaptable": "적응 가능한",
    "flexible": "유연한",
    "rigid": "경직된",
    "fixed": "고정된",
    "dynamic": "동적",
    "static": "정적",
    "variable": "가변",
    "immutable": "불변",
    "mutable": "가변",
    "constant": "상수",
    "volatile": "휘발성",
    "persistent": "영구적",
    "transient": "일시적",
    "temporary": "임시",
    "permanent": "영구",
    "ephemeral": "일시적",
    "durable": "내구성",
    "fragile": "취약한",
    "brittle": "부서지기 쉬운",
    "robust": "강력한",
    "resilient": "복원력 있는",
    "sturdy": "견고한",
    "solid": "견고한",
    "weak": "약한",
    "strong": "강한",
    "powerful": "강력한",
    "capable": "유능한",
    "competent": "유능한",
    "proficient": "능숙한",
    "skilled": "숙련된",
    "experienced": "경험이 있는",
    "inexperienced": "경험이 없는",
    "novice": "초보자",
    "beginner": "초보자",
    "intermediate": "중급자",
    "advanced": "고급",
    "expert": "전문가",
    "master": "마스터",
    "senior": "시니어",
    "junior": "주니어",
    "lead": "리드",
    "principal": "수석",
    "staff": "스태프",
    "distinguished": "저명한",
    "fellow": "펠로우",
    "emeritus": "명예",
    
    # Common prepositions and conjunctions
    "and": "및",
    "or": "또는",
    "but": "그러나",
    "with": "와 함께",
    "without": "없이",
    "for": "위한",
    "from": "에서",
    "to": "에",
    "in": "에서",
    "on": "에",
    "at": "에서",
    "by": "에 의해",
    "through": "통해",
    "via": "를 통해",
    "using": "사용하여",
    "across": "전반에 걸쳐",
    "between": "사이",
    "among": "사이에",
    "within": "내에",
    "outside": "외부",
    "inside": "내부",
    "before": "이전",
    "after": "이후",
    "during": "동안",
    "while": "동안",
    "when": "때",
    "where": "곳",
    "which": "어느",
    "that": "것",
    "who": "누구",
    "whom": "누구를",
    "whose": "누구의",
    "why": "왜",
    "how": "어떻게",
    "what": "무엇",
    "if": "만약",
    "unless": "하지 않는 한",
    "until": "까지",
    "since": "이후",
    "as": "처럼",
    "like": "같은",
    "than": "보다",
    "such": "그러한",
    "so": "그래서",
    "therefore": "따라서",
    "thus": "따라서",
    "hence": "따라서",
    "consequently": "결과적으로",
    "accordingly": "따라서",
    "however": "그러나",
    "nevertheless": "그럼에도 불구하고",
    "nonetheless": "그럼에도 불구하고",
    "yet": "아직",
    "still": "여전히",
    "already": "이미",
    "just": "방금",
    "only": "오직",
    "also": "또한",
    "too": "또한",
    "even": "심지어",
    "very": "매우",
    "quite": "상당히",
    "rather": "오히려",
    "pretty": "꽤",
    "fairly": "상당히",
    "relatively": "상대적으로",
    "absolutely": "절대적으로",
    "completely": "완전히",
    "totally": "전적으로",
    "entirely": "전적으로",
    "fully": "완전히",
    "partially": "부분적으로",
    "partly": "부분적으로",
    "somewhat": "다소",
    "slightly": "약간",
    "barely": "거의 ~하지 않는",
    "hardly": "거의 ~하지 않는",
    "scarcely": "거의 ~하지 않는",
    "nearly": "거의",
    "almost": "거의",
    "approximately": "대략",
    "roughly": "대략",
    "about": "약",
    "around": "약",
    "exactly": "정확히",
    "precisely": "정확히",
    "specifically": "구체적으로",
    "particularly": "특히",
    "especially": "특히",
    "mainly": "주로",
    "mostly": "대부분",
    "primarily": "주로",
    "chiefly": "주로",
    "predominantly": "주로",
    "largely": "대부분",
    "generally": "일반적으로",
    "typically": "일반적으로",
    "usually": "일반적으로",
    "normally": "일반적으로",
    "commonly": "일반적으로",
    "frequently": "자주",
    "often": "자주",
    "sometimes": "때때로",
    "occasionally": "때때로",
    "rarely": "드물게",
    "seldom": "드물게",
    "never": "절대 ~하지 않음",
    "always": "항상",
    "ever": "언제나",
    "forever": "영원히",
    "constantly": "계속해서",
    "continually": "계속해서",
    "continuously": "지속적으로",
    "repeatedly": "반복적으로",
    "regularly": "정기적으로",
    "periodically": "주기적으로",
    "intermittently": "간헐적으로",
    "sporadically": "산발적으로",
    "randomly": "무작위로",
    "arbitrarily": "임의로",
    "deliberately": "의도적으로",
    "intentionally": "의도적으로",
    "purposefully": "의도적으로",
    "accidentally": "우연히",
    "incidentally": "우연히",
    "unintentionally": "의도치 않게",
    "inadvertently": "무심코",
    "mistakenly": "실수로",
    "erroneously": "잘못",
    "incorrectly": "잘못",
    "wrongly": "잘못",
    "improperly": "부적절하게",
    "inappropriately": "부적절하게",
    "unsuitably": "부적합하게",
    "properly": "적절하게",
    "appropriately": "적절하게",
    "suitably": "적합하게",
    "correctly": "올바르게",
    "accurately": "정확하게",
    "precisely": "정확하게",
    "exactly": "정확하게",
    "closely": "밀접하게",
    "tightly": "밀접하게",
    "loosely": "느슨하게",
    "firmly": "확고하게",
    "solidly": "견고하게",
    "strongly": "강하게",
    "weakly": "약하게",
    "lightly": "가볍게",
    "heavily": "무겁게",
    "deeply": "깊이",
    "shallowly": "얕게",
    "broadly": "넓게",
    "widely": "넓게",
    "narrowly": "좁게",
    "extensively": "광범위하게",
    "intensively": "집중적으로",
    "comprehensively": "포괄적으로",
    "thoroughly": "철저히",
    "carefully": "신중하게",
    "cautiously": "조심스럽게",
    "prudently": "신중하게",
    "wisely": "현명하게",
    "foolishly": "어리석게",
    "recklessly": "무모하게",
    "carelessly": "부주의하게",
    "hastily": "서둘러",
    "quickly": "빠르게",
    "rapidly": "빠르게",
    "swiftly": "신속하게",
    "speedily": "빠르게",
    "slowly": "느리게",
    "gradually": "점진적으로",
    "progressively": "점진적으로",
    "incrementally": "점진적으로",
    "stepwise": "단계적으로",
    "sequentially": "순차적으로",
    "serially": "직렬로",
    "concurrently": "동시에",
    "simultaneously": "동시에",
    "parallel": "병렬로",
    "asynchronously": "비동기적으로",
    "synchronously": "동기적으로",
    "immediately": "즉시",
    "instantly": "즉시",
    "promptly": "즉시",
    "directly": "직접",
    "indirectly": "간접적으로",
    "explicitly": "명시적으로",
    "implicitly": "암시적으로",
    "clearly": "명확하게",
    "obviously": "명백하게",
    "evidently": "명백하게",
    "apparently": "분명히",
    "seemingly": "겉보기에",
    "ostensibly": "표면적으로",
    "allegedly": "주장된 바에 따르면",
    "supposedly": "추정상",
    "presumably": "추정컨대",
    "likely": "아마도",
    "probably": "아마",
    "possibly": "가능하게",
    "perhaps": "아마도",
    "maybe": "아마도",
    "certainly": "확실히",
    "definitely": "확실히",
    "surely": "확실히",
    "undoubtedly": "의심할 여지 없이",
    "unquestionably": "의문의 여지 없이",
    "indisputably": "명백히",
    "arguably": "논란의 여지가 있지만",
    "debatably": "논쟁의 여지가 있게",
    "theoretically": "이론적으로",
    "practically": "실질적으로",
    "realistically": "현실적으로",
    "ideally": "이상적으로",
    "optimally": "최적으로",
    "maximally": "최대한",
    "minimally": "최소한",
    "sufficiently": "충분히",
    "adequately": "적절하게",
    "insufficiently": "불충분하게",
    "excessively": "과도하게",
    "extremely": "극도로",
    "highly": "매우",
    "greatly": "크게",
    "significantly": "상당히",
    "substantially": "상당히",
    "considerably": "상당히",
    "moderately": "적당히",
    "slightly": "약간",
    "marginally": "근소하게",
    "trivially": "사소하게",
    "negligibly": "무시할 정도로",
}

# Technical terms to preserve (case-insensitive)
PRESERVE_TECH = {
    # All brand names, protocols, tools from previous list...
    "Stripe", "PayPal", "Square", "AWS", "Azure", "Google", "GitHub", "GitLab",
    "REST", "RESTful", "GraphQL", "gRPC", "HTTP", "HTTPS", "WebSocket",
    "Kubernetes", "Docker", "Terraform", "React", "Vue", "Angular",
    "FastAPI", "Django", "Flask", "PostgreSQL", "MySQL", "MongoDB", "Redis",
    "OAuth", "JWT", "JSON", "YAML", "XML",
    "Node.js", "Python", "JavaScript", "TypeScript", "Java", "Go", "Rust",
    "API", "SDK", "CLI", "CI/CD", "TDD", "BDD", "DDD",
    "Temporal", "Kafka", "RabbitMQ", "Prometheus", "Grafana",
    "Git", "npm", "pip", "Maven", "Gradle",
    # Add more as needed...
}

def preserve_terms(text: str) -> Tuple[str, Dict[str, str]]:
    """Preserve URLs, code, links, and technical terms"""
    placeholders = {}
    counter = 0
    
    # URLs
    for url in re.findall(r'https?://[^\s)\]>]+', text):
        ph = f"__URL{counter}__"
        placeholders[ph] = url
        text = text.replace(url, ph)
        counter += 1
    
    # Inline code
    for code in re.findall(r'`[^`]+`', text):
        ph = f"__CODE{counter}__"
        placeholders[ph] = code
        text = text.replace(code, ph)
        counter += 1
    
    # Markdown links
    for match in re.finditer(r'\[([^\]]+)\]\(([^\)]+)\)', text):
        ph = f"__LINK{counter}__"
        placeholders[ph] = match.group(0)
        text = text.replace(match.group(0), ph)
        counter += 1
    
    # Technical terms
    for term in sorted(PRESERVE_TECH, key=len, reverse=True):
        pattern = re.compile(r'\b' + re.escape(term) + r'\b', re.IGNORECASE)
        matches = list(pattern.finditer(text))
        for match in reversed(matches):
            original = match.group(0)
            ph = f"__TECH{counter}__"
            placeholders[ph] = original
            text = text[:match.start()] + ph + text[match.end():]
            counter += 1
    
    return text, placeholders

def restore_terms(text: str, placeholders: Dict[str, str]) -> str:
    """Restore preserved terms"""
    for ph, original in placeholders.items():
        text = text.replace(ph, original)
    return text

def translate_text(text: str) -> str:
    """Translate text to Korean"""
    if not text.strip():
        return text
    
    # Preserve technical terms
    text, placeholders = preserve_terms(text)
    
    # Apply translations (sorted by length, longest first)
    for eng, kor in sorted(MEGA_TRANSLATIONS.items(), key=lambda x: len(x[0]), reverse=True):
        pattern = r'\b' + re.escape(eng) + r'\b'
        text = re.sub(pattern, kor, text, flags=re.IGNORECASE)
    
    # Restore preserved terms
    text = restore_terms(text, placeholders)
    
    return text

def process_file(source: Path, dest: Path):
    """Process and translate a file"""
    with open(source, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    result = []
    in_code = False
    in_yaml = False
    yaml_count = 0
    
    for line in lines:
        stripped = line.strip()
        
        # YAML frontmatter
        if stripped == '---':
            yaml_count += 1
            result.append(line)
            if yaml_count == 1:
                in_yaml = True
            elif yaml_count == 2:
                in_yaml = False
            continue
        
        # Inside YAML
        if in_yaml:
            if stripped.startswith('description:'):
                parts = line.split(':', 1)
                if len(parts) == 2:
                    key = parts[0]
                    value = parts[1]
                    translated_value = translate_text(value)
                    result.append(f"{key}:{translated_value}")
                else:
                    result.append(line)
            else:
                result.append(line)
            continue
        
        # Code blocks
        if stripped.startswith('```'):
            in_code = not in_code
            result.append(line)
            continue
        
        if in_code:
            result.append(line)
            continue
        
        # Empty lines
        if not stripped:
            result.append(line)
            continue
        
        # Translate
        result.append(translate_text(line))
    
    # Write
    dest.parent.mkdir(parents=True, exist_ok=True)
    with open(dest, 'w', encoding='utf-8') as f:
        f.writelines(result)

def main():
    source_dir = Path("/Users/kevinjang0301/workprivate/agentsAI/plugins")
    dest_dir = Path("/Users/kevinjang0301/workprivate/agentsAI/pluginsK")
    
    md_files = sorted(source_dir.rglob("*.md"))
    total = len(md_files)
    
    print(f"Translating {total} files to 100% Korean...")
    
    success = 0
    for i, source in enumerate(md_files, 1):
        rel_path = source.relative_to(source_dir)
        dest = dest_dir / rel_path
        
        try:
            process_file(source, dest)
            success += 1
            if i % 30 == 0 or i == total:
                print(f"[{i}/{total}] {rel_path}")
        except Exception as e:
            print(f"ERROR [{i}/{total}] {rel_path}: {e}")
    
    print(f"\n✓ All {total} files translated to 100% Korean")
    print(f"  Files translated: {success}/{total}")

if __name__ == "__main__":
    main()

